# Python Basic Programming Assignment 8

### 1. Write a Python Program to Add Two Matrices?

In [6]:
import numpy as np
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

arr1= np.array(X)+np.array(Y)
print("Add two matrics :\n",arr1)


Add two matrics :
 [[17 15  4]
 [10 12  9]
 [11 13 18]]


### 2. Write a Python Program to Multiply Two Matrices?

In [7]:
arr1= np.array(X)*np.array(Y)
print("Mulitply two matrics :\n",arr1)

Mulitply two matrics :
 [[60 56  3]
 [24 35 18]
 [28 40 81]]


### 3. Write a Python Program to Transpose a Matrix?

In [11]:
print("original matrics :\n",np.array(X))
print("Transpose matrics :\n",np.array(X).T)

original matrics :
 [[12  7  3]
 [ 4  5  6]
 [ 7  8  9]]
Transpose matrics :
 [[12  4  7]
 [ 7  5  8]
 [ 3  6  9]]


### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [31]:
text="Write a Python Program to Sort Words in Alphabetic Order"
print("Sorted Text :\n"," ".join(sorted(text.lower().split())))

Sorted Text :
 a alphabetic in order program python sort to words write


### 5.Write a Python Program to Remove Punctuation From a String?

In [33]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
my_str = input("Enter a string with punctuations :\n ")
print("\nEntered string is :\n ",my_str)
no_punct = ""
for char in my_str:
    if char not in punctuations:
        no_punct = no_punct + char
print("\nAfter removing punctuations, the string is : \n",no_punct)

Enter a string with punctuations :
 Write a Python Program to Remove@@#% Pu!!!!!!nctuation%!&?> From a String?

Entered string is :
  Write a Python Program to Remove@@#% Pu!!!!!!nctuation%!&?> From a String?

After removing punctuations, the string is : 
 Write a Python Program to Remove Punctuation From a String
